# Generated by Django 3.2.6 on 2021-08-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LOIs',
            new_name='LOIModel',
        ),
    ]
