# Generated by Django 3.2.6 on 2021-08-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_lois_loimodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loimodel',
            table='LOITable',
        ),
    ]
