# Generated by Django 3.2.6 on 2021-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_loimodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOIModelNew',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
                ('advice', models.CharField(max_length=1000)),
                ('added', models.CharField(max_length=1000)),
                ('updated', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'LOITableNew',
            },
        ),
        migrations.AlterField(
            model_name='loimodel',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
