# Generated by Django 3.2.6 on 2021-08-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210822_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loimodel',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='loimodelnew',
            name='updated',
        ),
    ]
